/*  cudaVUIstd.h

  vector management functions for data type "ui"
  ("unsigned index" = size_t, the data type for indexing and addressing).

  Copyright (c) 1996-2017 by OptiCode - Dr. Martin Sander Software Dev.
  All Rights Reserved.
*/

#ifndef __CUDAVUISTD_H
#define __CUDAVUISTD_H

#if defined _WIN64
   #if !defined( __CUDAVUQSTD_H )
      #include <cudaVUQstd.h>
   #endif
   #define cudaVUI_vector            cudaVUQ_vector
   #define cudaVUI_vector0           cudaVUQ_vector0
   #define cudaVUI_pinnedVector      cudaVUQ_pinnedVector
   #define cudaVUI_pinnedVector0     cudaVUQ_pinnedVector0
   #define cudaVUI_Pelement          cudaVUQ_Pelement
   #define cudaVUI_element           cudaVUQ_element
   #define cudaVUI_getElement        cudaVUQ_getElement
   #define cusdVUI_getElement        cusdVUQ_getElement
   #define cudaVUI_setElement        cudaVUQ_setElement
   #define cusdVUI_setElement        cusdVUQ_setElement
   #define cudaVUI_equ0              cudaVUQ_equ0
   #define cudaVUI_equC              cudaVUQ_equC
   #define cusdVUI_equC              cusdVUQ_equC
   #define cudaVUI_equV              cudaVUQ_equV
   #define cudaVUI_equVhost          cudaVUQ_equVhost
   #define VUI_equVdevice            VUQ_equVdevice
   #define cudaVUI_ramp              cudaVUQ_ramp
   #define cusdVUI_ramp              cusdVUQ_ramp
   #define cudaVUI_randomLC          cudaVUQ_randomLC
   #define cusdVUI_randomLC          cusdVUQ_randomLC
   #define cudaVUI_random            cudaVUQ_random
   #define cusdVUI_random            cusdVUQ_random
   #define cudaV_UItoU               cudaV_UQtoU
   #define cudaV_UtoUI               cudaV_UtoUQ
   #define cudaV_UItoUB              cudaV_UQtoUB
   #define cudaV_UBtoUI              cudaV_UBtoUQ
   #define cudaV_UItoUS              cudaV_UQtoUS
   #define cudaV_UStoUI              cudaV_UStoUQ
   #define cudaV_ULtoUI              cudaV_ULtoUQ
   #define cudaV_UItoUL              cudaV_UQtoUL
   #define cudaV_UQtoUI              cudaVUQ_equV
   #define cudaV_UItoUQ              cudaVUQ_equV
   #define cudaV_UItoF               cudaV_UQtoF
   #define cudaV_UItoD               cudaV_UQtoD
   #define cudaVUI_reflect           cudaVUQ_reflect
   #define cudaVUI_rev               cudaVUQ_rev
   #define cudaVUI_rotate            cudaVUQ_rotate
   #define cudaVUI_delete            cudaVUQ_delete
   #define cudaVUI_insert            cudaVUQ_insert
   #define cusdVUI_insert            cusdVUQ_insert
   #define cudaVUI_sort              cudaVUQ_sort
   #define cudaVUI_sortind           cudaVUQ_sortind
   #define cudaVUI_subvector         cudaVUQ_subvector
   #define cudaVUI_subvector_equC    cudaVUQ_subvector_equC
   #define cusdVUI_subvector_equC    cusdVUQ_subvector_equC
   #define cudaVUI_subvector_equV    cudaVUQ_subvector_equV
   #define cudaVUI_indpick           cudaVUQ_indpick
   #define cudaVUI_indput            cudaVUQ_indput
   #define cudaVUI_searchC           cudaVUQ_searchC
   #define cusdVUI_searchC           cusdVUQ_searchC
   #define cudaVUI_searchV           cudaVUQ_searchV
   #define cudaVUI_sum               cudaVUQ_sum
   #define cudaVUI_fsum              cudaVUQ_fsum
   #define cudaVUI_mean              cudaVUQ_mean
   #define cudaVUI_max               cudaVUQ_max
   #define cudaVUI_min               cudaVUQ_min
   #define cudaVUI_maxind            cudaVUQ_maxind
   #define cudaVUI_minind            cudaVUQ_minind
   #define cusdVUI_sum               cusdVUQ_sum
   #define cusdVUI_fsum              cusdVUQ_fsum
   #define cusdVUI_mean              cusdVUQ_mean
   #define cusdVUI_max               cusdVUQ_max
   #define cusdVUI_min               cusdVUQ_min
   #define cusdVUI_maxind            cusdVUQ_maxind
   #define cusdVUI_minind            cusdVUQ_minind
   #define cudaVUI_iselementC        cudaVUQ_iselementC
   #define cusdVUI_iselementC        cusdVUQ_iselementC
   #define cudaVUI_iselementV        cudaVUQ_iselementV
   #define cudaVUI_fprint            cudaVUQ_fprint
   #define cudaVUI_print             cudaVUQ_print
   #define cudaVUI_cprint            cudaVUQ_cprint
   #define cudaVUI_read              cudaVUQ_read
   #define cudaVUI_write             cudaVUQ_write
   #define cudaVUI_store             cudaVUQ_store
   #define cudaVUI_recall            cudaVUQ_recall
   #define cudaVUI_fprint_buf        cudaVUQ_fprint_buf
   #define cudaVUI_print_buf         cudaVUQ_print_buf
   #define cudaVUI_cprint_buf        cudaVUQ_cprint_buf
   #define cudaVUI_read_buf          cudaVUQ_read_buf
   #define cudaVUI_write_buf         cudaVUQ_write_buf
   #define cudaVUI_store_buf         cudaVUQ_store_buf
   #define cudaVUI_recall_buf        cudaVUQ_recall_buf

   #define VUIcu_equ0              VUQcu_equ0
   #define VUIcu_equC              VUQcu_equC
   #define VUIcu_equV              VUQcu_equV
   #define VUIcu_ramp              VUQcu_ramp
   #define Vcu_UItoU               Vcu_UQtoU
   #define Vcu_UtoUI               Vcu_UtoUQ
   #define Vcu_UItoUB              Vcu_UQtoUB
   #define Vcu_UBtoUI              Vcu_UBtoUQ
   #define Vcu_UItoUS              Vcu_UQtoUS
   #define Vcu_UStoUI              Vcu_UStoUQ
   #define Vcu_ULtoUI              Vcu_ULtoUQ
   #define Vcu_UItoUL              Vcu_UQtoUL
   #define Vcu_UQtoUI              VUQcu_equV
   #define Vcu_UItoUQ              VUQcu_equV
   #define Vcu_UItoF               Vcu_UQtoF
   #define Vcu_UItoD               Vcu_UQtoD
   #define VUIcu_reflect           VUQcu_reflect
   #define VUIcu_rev               VUQcu_rev
   #define VUIcu_rotate            VUQcu_rotate
   #define VUIcu_delete            VUQcu_delete
   #define VUIcu_insert            VUQcu_insert
   #define VUIcu_sort              VUQcu_sort
   #define VUIcu_sortind           VUQcu_sortind
   #define VUIcu_subvector         VUQcu_subvector
   #define VUIcu_subvector_equC    VUQcu_subvector_equC
   #define VUIcu_subvector_equV    VUQcu_subvector_equV
   #define VUIcu_indpick           VUQcu_indpick
   #define VUIcu_indput            VUQcu_indput
   #define VUIcu_searchC           VUQcu_searchC
   #define VUIcu_searchV           VUQcu_searchV
   #define VUIcu_sum               VUQcu_sum
   #define VUIcu_fsum              VUQcu_fsum
   #define VUIcu_mean              VUQcu_mean
   #define VUIcu_max               VUQcu_max
   #define VUIcu_min               VUQcu_min
   #define VUIcu_maxind            VUQcu_maxind
   #define VUIcu_minind            VUQcu_minind
   #define VUIcu_iselementC        VUQcu_iselementC
   #define VUIcu_iselementV        VUQcu_iselementV
#else   /* Win32  */
   #if !defined( __CUDAVUSTD_H )
      #include <cudaVUstd.h>
   #endif
   #define cudaVUI_vector            cudaVU_vector
   #define cudaVUI_vector0           cudaVU_vector0
   #define cudaVUI_pinnedVector      cudaVU_pinnedVector
   #define cudaVUI_pinnedVector0     cudaVU_pinnedVector0
   #define cudaVUI_Pelement          cudaVU_Pelement
   #define cudaVUI_element           cudaVU_element
   #define cudaVUI_getElement        cudaVU_getElement
   #define cusdVUI_getElement        cusdVU_getElement
   #define cudaVUI_setElement        cudaVU_setElement
   #define cusdVUI_setElement        cusdVU_setElement
   #define cudaVUI_equ0              cudaVU_equ0
   #define cudaVUI_equC              cudaVU_equC
   #define cusdVUI_equC              cusdVU_equC
   #define cudaVUI_equV              cudaVU_equV
   #define cudaVUI_equVhost          cudaVU_equVhost
   #define VUI_equVdevice            VU_equVdevice
   #define cudaVUI_ramp              cudaVU_ramp
   #define cusdVUI_ramp              cusdVU_ramp
   #define cudaVUI_randomLC          cudaVU_randomLC
   #define cusdVUI_randomLC          cusdVU_randomLC
   #define cudaVUI_random            cudaVU_random
   #define cusdVUI_random            cusdVU_random
   #define cudaV_UItoU               cudaVU_equV
   #define cudaV_UtoUI               cudaVU_equV
   #define cudaV_UItoUB              cudaV_UtoUB
   #define cudaV_UBtoUI              cudaV_UBtoU
   #define cudaV_UItoUS              cudaV_UtoUS
   #define cudaV_UStoUI              cudaV_UStoU
   #define cudaV_ULtoUI              cudaV_ULtoU
   #define cudaV_UItoUL              cudaV_UtoUL
   #define cudaV_UItoF               cudaV_UtoF
   #define cudaV_UItoD               cudaV_UtoD
   #define cudaVUI_reflect           cudaVU_reflect
   #define cudaVUI_rev               cudaVU_rev
   #define cudaVUI_rotate            cudaVU_rotate
   #define cudaVUI_delete            cudaVU_delete
   #define cudaVUI_insert            cudaVU_insert
   #define cusdVUI_insert            cusdVU_insert
   #define cudaVUI_sort              cudaVU_sort
   #define cudaVUI_sortind           cudaVU_sortind
   #define cudaVUI_subvector         cudaVU_subvector
   #define cudaVUI_subvector_equC    cudaVU_subvector_equC
   #define cusdVUI_subvector_equC    cusdVU_subvector_equC
   #define cudaVUI_subvector_equV    cudaVU_subvector_equV
   #define cudaVUI_indpick           cudaVU_indpick
   #define cudaVUI_indput            cudaVU_indput
   #define cudaVUI_searchC           cudaVU_searchC
   #define cusdVUI_searchC           cusdVU_searchC
   #define cudaVUI_searchV           cudaVU_searchV
   #define cudaVUI_sum               cudaVU_sum
   #define cudaVUI_fsum              cudaVU_fsum
   #define cudaVUI_mean              cudaVU_mean
   #define cudaVUI_max               cudaVU_max
   #define cudaVUI_min               cudaVU_min
   #define cudaVUI_maxind            cudaVU_maxind
   #define cudaVUI_minind            cudaVU_minind
   #define cusdVUI_sum               cusdVU_sum
   #define cusdVUI_fsum              cusdVU_fsum
   #define cusdVUI_mean              cusdVU_mean
   #define cusdVUI_max               cusdVU_max
   #define cusdVUI_min               cusdVU_min
   #define cusdVUI_maxind            cusdVU_maxind
   #define cusdVUI_minind            cusdVU_minind
   #define cudaVUI_iselementC        cudaVU_iselementC
   #define cusdVUI_iselementC        cusdVU_iselementC
   #define cudaVUI_iselementV        cudaVU_iselementV
   #define cudaVUI_fprint            cudaVU_fprint
   #define cudaVUI_print             cudaVU_print
   #define cudaVUI_cprint            cudaVU_cprint
   #define cudaVUI_read              cudaVU_read
   #define cudaVUI_write             cudaVU_write
   #define cudaVUI_store             cudaVU_store
   #define cudaVUI_recall            cudaVU_recall
   #define cudaVUI_fprint_buf        cudaVU_fprint_buf
   #define cudaVUI_print_buf         cudaVU_print_buf
   #define cudaVUI_cprint_buf        cudaVU_cprint_buf
   #define cudaVUI_read_buf          cudaVU_read_buf
   #define cudaVUI_write_buf         cudaVU_write_buf
   #define cudaVUI_store_buf         cudaVU_store_buf
   #define cudaVUI_recall_buf        cudaVU_recall_buf

   #define VUIcu_equ0              VUcu_equ0
   #define VUIcu_equC              VUcu_equC
   #define VUIcu_equV              VUcu_equV
   #define VUIcu_ramp              VUcu_ramp
   #define Vcu_UItoUB              Vcu_UtoUB
   #define Vcu_UBtoUI              Vcu_UBtoU
   #define Vcu_UItoUS              Vcu_UtoUS
   #define Vcu_UStoUI              Vcu_UStoU
   #define Vcu_ULtoUI              Vcu_ULtoU
   #define Vcu_UItoUL              Vcu_UtoUL
   #define Vcu_UtoUI               VUcu_equV
   #define Vcu_UItoU               VUcu_equV
   #define Vcu_UItoF               Vcu_UtoF
   #define Vcu_UItoD               Vcu_UtoD
   #define VUIcu_reflect           VUcu_reflect
   #define VUIcu_rev               VUcu_rev
   #define VUIcu_rotate            VUcu_rotate
   #define VUIcu_delete            VUcu_delete
   #define VUIcu_insert            VUcu_insert
   #define VUIcu_sort              VUcu_sort
   #define VUIcu_sortind           VUcu_sortind
   #define VUIcu_subvector         VUcu_subvector
   #define VUIcu_subvector_equC    VUcu_subvector_equC
   #define VUIcu_subvector_equV    VUcu_subvector_equV
   #define VUIcu_indpick           VUcu_indpick
   #define VUIcu_indput            VUcu_indput
   #define VUIcu_searchC           VUcu_searchC
   #define VUIcu_searchV           VUcu_searchV
   #define VUIcu_sum               VUcu_sum
   #define VUIcu_fsum              VUcu_fsum
   #define VUIcu_mean              VUcu_mean
   #define VUIcu_max               VUcu_max
   #define VUIcu_min               VUcu_min
   #define VUIcu_maxind            VUcu_maxind
   #define VUIcu_minind            VUcu_minind
   #define VUIcu_iselementC        VUcu_iselementC
   #define VUIcu_iselementV        VUcu_iselementV
#endif  /*  _WIN64 */

#endif /* __cudaVUISTD_H  */

