/*     MatAll.h

      includes all header files for the MatrixLib part of OptiVec

      Copyright (c) 1996-2017 by OptiCode - Dr. Martin Sander Software Dev.
*/

#ifdef __cplusplus
    #include <newcplx.h>
#else
    #include <cmath.h>
#endif
#include <MFstd.h>
#include <MDstd.h>
#include <MEstd.h>
#include <MCFstd.h>
#include <MCDstd.h>
#include <MCEstd.h>
#include <MBIstd.h>
#include <MUBstd.h>
#include <MSIstd.h>
#include <MUSstd.h>
#include <MIstd.h>
#include <MUstd.h>
#include <MLIstd.h>
#include <MULstd.h>
#include <MQIstd.h>
#ifdef _WIN64
    #include <MUQstd.h>
#endif
#include <MUIstd.h>
#include <MGraph.h>

