/*    VecAll.h

      includes all header files belonging to and needed by
      the VectorLib part of OptiVec

      Copyright (c) 1996-2016 by OptiCode - Dr. Martin Sander Software Dev.
*/

#ifdef __cplusplus
    #include <newcplx.h>
#endif
#include <cmath.h>
#include <VecLib.h>
#include <VFstd.h>
#include <VDstd.h>
#include <VEstd.h>
#include <VCFstd.h>
#include <VCDstd.h>
#include <VCEstd.h>
#include <VPFstd.h>
#include <VPDstd.h>
#include <VPEstd.h>
#include <VBIstd.h>
#include <VSIstd.h>
#include <VIstd.h>
#include <VLIstd.h>
#include <VQIstd.h>
#include <VUBstd.h>
#include <VUSstd.h>
#include <VUstd.h>
#include <VULstd.h>
#include <VUIstd.h>
#include <VFmath.h>
#include <VDmath.h>
#include <VEmath.h>
#include <VCFmath.h>
#include <VCDmath.h>
#include <VCEmath.h>
#include <VPFmath.h>
#include <VPDmath.h>
#include <VPEmath.h>
#include <VBImath.h>
#include <VSImath.h>
#include <VImath.h>
#include <VLImath.h>
#include <VQImath.h>
#include <VUBmath.h>
#include <VUSmath.h>
#include <VUmath.h>
#include <VULmath.h>
#ifdef _WIN64
#include <VUQstd.h>
#include <VUQmath.h>
#endif
#include <VUImath.h>
#include <Vgraph.h>
#include <ovxmath.h>

